# Generated by Django 6.1.1 on 2026-09-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SOSRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(help_text='Original natural language request submitted by victim or reporter')),
                ('urgency', models.CharField(choices=[('CRITICAL', 'Critical - Life Threatening'), ('HIGH', 'High - Urgent Assistance Required'), ('MEDIUM', 'Medium - Essential Supplies Needed'), ('LOW', 'Low - General Support')], default='MEDIUM', max_length=20)),
                ('category', models.CharField(choices=[('RESCUE', 'Rescue / Trapped'), ('MEDICAL', 'Medical Emergency'), ('FOOD_WATER', 'Food & Clean Water'), ('SHELTER', 'Shelter & Blanket'), ('EVACUATION', 'Evacuation / Transport'), ('OTHER', 'General Need')], default='FOOD_WATER', max_length=30)),
                ('items', models.JSONField(blank=True, default=list, help_text='Parsed list of items or services needed')),
                ('address', models.CharField(default='Unknown Location', max_length=255)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('people_count', models.IntegerField(default=1)),
                ('contact_name', models.CharField(default='Anonymous Victim', max_length=100)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('UNCLAIMED', 'Unclaimed'), ('CLAIMED', 'Claimed by Volunteer'), ('IN_PROGRESS', 'Aid en route'), ('RESOLVED', 'Resolved & Delivered')], default='UNCLAIMED', max_length=20)),
                ('volunteer_name', models.CharField(blank=True, default='', max_length=100)),
                ('volunteer_phone', models.CharField(blank=True, default='', max_length=50)),
                ('volunteer_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
